// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO pockets.accounts (name, icon, colour, target_amount, is_reserve)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateAccountParams struct {
	Name         string         `json:"name"`
	Icon         string         `json:"icon"`
	Colour       string         `json:"colour"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	IsReserve    bool           `json:"is_reserve"`
}

// Cellarium Pockets — sqlc query definitions for accounts
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Icon,
		arg.Colour,
		arg.TargetAmount,
		arg.IsReserve,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, icon, colour, target_amount, is_reserve, sort_order, created_at
FROM pockets.accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (PocketsAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i PocketsAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Colour,
		&i.TargetAmount,
		&i.IsReserve,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(CASE WHEN is_inflow THEN amount ELSE -amount END), 0)::NUMERIC(12,2) AS balance
FROM pockets.transactions
WHERE account_id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const getFirstReserveAccountID = `-- name: GetFirstReserveAccountID :one
SELECT id FROM pockets.accounts WHERE is_reserve = TRUE ORDER BY sort_order ASC, id ASC LIMIT 1
`

func (q *Queries) GetFirstReserveAccountID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getFirstReserveAccountID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, icon, colour, target_amount, is_reserve, sort_order, created_at
FROM pockets.accounts
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]PocketsAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsAccount
	for rows.Next() {
		var i PocketsAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Colour,
			&i.TargetAmount,
			&i.IsReserve,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE pockets.accounts
SET name = $1, icon = $2, colour = $3, target_amount = $4,
    is_reserve = $5, sort_order = $6
WHERE id = $7
`

type UpdateAccountParams struct {
	Name         string         `json:"name"`
	Icon         string         `json:"icon"`
	Colour       string         `json:"colour"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	IsReserve    bool           `json:"is_reserve"`
	SortOrder    int32          `json:"sort_order"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Name,
		arg.Icon,
		arg.Colour,
		arg.TargetAmount,
		arg.IsReserve,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
