// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PocketsAccount struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Icon         string             `json:"icon"`
	Colour       string             `json:"colour"`
	TargetAmount pgtype.Numeric     `json:"target_amount"`
	IsReserve    bool               `json:"is_reserve"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PocketsTopupRule struct {
	ID            int64              `json:"id"`
	AccountID     int64              `json:"account_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	EffectiveDate pgtype.Date        `json:"effective_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PocketsTransaction struct {
	ID               int64              `json:"id"`
	AccountID        int64              `json:"account_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	IsInflow         bool               `json:"is_inflow"`
	TxDate           pgtype.Date        `json:"tx_date"`
	Note             pgtype.Text        `json:"note"`
	IsAutoTopup      bool               `json:"is_auto_topup"`
	UserEdited       bool               `json:"user_edited"`
	IsInitialBalance bool               `json:"is_initial_balance"`
	TopupRuleID      pgtype.Int8        `json:"topup_rule_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
