// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Cellarium Pockets — sqlc query definitions for accounts
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error)
	// Cellarium Pockets — sqlc query definitions for top-up rules
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateTopupRule(ctx context.Context, arg CreateTopupRuleParams) (int64, error)
	// Cellarium Pockets — sqlc query definitions for transactions
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error)
	DeleteTopupRule(ctx context.Context, arg DeleteTopupRuleParams) error
	GetAccount(ctx context.Context, id int64) (PocketsAccount, error)
	GetAccountBalance(ctx context.Context, accountID int64) (pgtype.Numeric, error)
	GetAutoTopupForDate(ctx context.Context, arg GetAutoTopupForDateParams) (PocketsTransaction, error)
	GetFirstReserveAccountID(ctx context.Context) (int64, error)
	GetTopupRule(ctx context.Context, id int64) (PocketsTopupRule, error)
	GetTransaction(ctx context.Context, id int64) (PocketsTransaction, error)
	ListAccounts(ctx context.Context) ([]PocketsAccount, error)
	ListTopupRules(ctx context.Context, accountID int64) ([]PocketsTopupRule, error)
	ListTransactionsAll(ctx context.Context, accountID int64) ([]PocketsTransaction, error)
	ListTransactionsAuto(ctx context.Context, accountID int64) ([]PocketsTransaction, error)
	ListTransactionsTopups(ctx context.Context, accountID int64) ([]PocketsTransaction, error)
	ListTransactionsWithdrawals(ctx context.Context, accountID int64) ([]PocketsTransaction, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateAutoTopupAmount(ctx context.Context, arg UpdateAutoTopupAmountParams) error
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error
}

var _ Querier = (*Queries)(nil)
