// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: topup_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopupRule = `-- name: CreateTopupRule :one

INSERT INTO pockets.topup_rules (account_id, amount, effective_date)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTopupRuleParams struct {
	AccountID     int64          `json:"account_id"`
	Amount        pgtype.Numeric `json:"amount"`
	EffectiveDate pgtype.Date    `json:"effective_date"`
}

// Cellarium Pockets — sqlc query definitions for top-up rules
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateTopupRule(ctx context.Context, arg CreateTopupRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTopupRule, arg.AccountID, arg.Amount, arg.EffectiveDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteTopupRule = `-- name: DeleteTopupRule :exec
DELETE FROM pockets.topup_rules WHERE id = $1 AND account_id = $2
`

type DeleteTopupRuleParams struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) DeleteTopupRule(ctx context.Context, arg DeleteTopupRuleParams) error {
	_, err := q.db.Exec(ctx, deleteTopupRule, arg.ID, arg.AccountID)
	return err
}

const getTopupRule = `-- name: GetTopupRule :one
SELECT id, account_id, amount, effective_date, created_at
FROM pockets.topup_rules
WHERE id = $1
`

func (q *Queries) GetTopupRule(ctx context.Context, id int64) (PocketsTopupRule, error) {
	row := q.db.QueryRow(ctx, getTopupRule, id)
	var i PocketsTopupRule
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.EffectiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTopupRules = `-- name: ListTopupRules :many
SELECT id, account_id, amount, effective_date, created_at
FROM pockets.topup_rules
WHERE account_id = $1
ORDER BY effective_date ASC, id ASC
`

func (q *Queries) ListTopupRules(ctx context.Context, accountID int64) ([]PocketsTopupRule, error) {
	rows, err := q.db.Query(ctx, listTopupRules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsTopupRule
	for rows.Next() {
		var i PocketsTopupRule
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.EffectiveDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
