// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO pockets.transactions (account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateTransactionParams struct {
	AccountID        int64          `json:"account_id"`
	Amount           pgtype.Numeric `json:"amount"`
	IsInflow         bool           `json:"is_inflow"`
	TxDate           pgtype.Date    `json:"tx_date"`
	Note             pgtype.Text    `json:"note"`
	IsAutoTopup      bool           `json:"is_auto_topup"`
	UserEdited       bool           `json:"user_edited"`
	IsInitialBalance bool           `json:"is_initial_balance"`
	TopupRuleID      pgtype.Int8    `json:"topup_rule_id"`
}

// Cellarium Pockets — sqlc query definitions for transactions
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.Amount,
		arg.IsInflow,
		arg.TxDate,
		arg.Note,
		arg.IsAutoTopup,
		arg.UserEdited,
		arg.IsInitialBalance,
		arg.TopupRuleID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAutoTopupForDate = `-- name: GetAutoTopupForDate :one
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE account_id = $1 AND is_auto_topup = TRUE AND tx_date = $2
LIMIT 1
`

type GetAutoTopupForDateParams struct {
	AccountID int64       `json:"account_id"`
	TxDate    pgtype.Date `json:"tx_date"`
}

func (q *Queries) GetAutoTopupForDate(ctx context.Context, arg GetAutoTopupForDateParams) (PocketsTransaction, error) {
	row := q.db.QueryRow(ctx, getAutoTopupForDate, arg.AccountID, arg.TxDate)
	var i PocketsTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.IsInflow,
		&i.TxDate,
		&i.Note,
		&i.IsAutoTopup,
		&i.UserEdited,
		&i.IsInitialBalance,
		&i.TopupRuleID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (PocketsTransaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i PocketsTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.IsInflow,
		&i.TxDate,
		&i.Note,
		&i.IsAutoTopup,
		&i.UserEdited,
		&i.IsInitialBalance,
		&i.TopupRuleID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsAll = `-- name: ListTransactionsAll :many
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE account_id = $1
ORDER BY tx_date DESC, id DESC
`

func (q *Queries) ListTransactionsAll(ctx context.Context, accountID int64) ([]PocketsTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsAll, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsTransaction
	for rows.Next() {
		var i PocketsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.IsInflow,
			&i.TxDate,
			&i.Note,
			&i.IsAutoTopup,
			&i.UserEdited,
			&i.IsInitialBalance,
			&i.TopupRuleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsAuto = `-- name: ListTransactionsAuto :many
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE account_id = $1 AND is_auto_topup = TRUE
ORDER BY tx_date DESC, id DESC
`

func (q *Queries) ListTransactionsAuto(ctx context.Context, accountID int64) ([]PocketsTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsAuto, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsTransaction
	for rows.Next() {
		var i PocketsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.IsInflow,
			&i.TxDate,
			&i.Note,
			&i.IsAutoTopup,
			&i.UserEdited,
			&i.IsInitialBalance,
			&i.TopupRuleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsTopups = `-- name: ListTransactionsTopups :many
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE account_id = $1 AND is_inflow = TRUE AND is_initial_balance = FALSE
ORDER BY tx_date DESC, id DESC
`

func (q *Queries) ListTransactionsTopups(ctx context.Context, accountID int64) ([]PocketsTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsTopups, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsTransaction
	for rows.Next() {
		var i PocketsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.IsInflow,
			&i.TxDate,
			&i.Note,
			&i.IsAutoTopup,
			&i.UserEdited,
			&i.IsInitialBalance,
			&i.TopupRuleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithdrawals = `-- name: ListTransactionsWithdrawals :many
SELECT id, account_id, amount, is_inflow, tx_date, note, is_auto_topup, user_edited, is_initial_balance, topup_rule_id, created_at
FROM pockets.transactions
WHERE account_id = $1 AND is_inflow = FALSE
ORDER BY tx_date DESC, id DESC
`

func (q *Queries) ListTransactionsWithdrawals(ctx context.Context, accountID int64) ([]PocketsTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsWithdrawals, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PocketsTransaction
	for rows.Next() {
		var i PocketsTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.IsInflow,
			&i.TxDate,
			&i.Note,
			&i.IsAutoTopup,
			&i.UserEdited,
			&i.IsInitialBalance,
			&i.TopupRuleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoTopupAmount = `-- name: UpdateAutoTopupAmount :exec
UPDATE pockets.transactions
SET amount = $1, topup_rule_id = $2
WHERE id = $3 AND user_edited = FALSE
`

type UpdateAutoTopupAmountParams struct {
	Amount      pgtype.Numeric `json:"amount"`
	TopupRuleID pgtype.Int8    `json:"topup_rule_id"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateAutoTopupAmount(ctx context.Context, arg UpdateAutoTopupAmountParams) error {
	_, err := q.db.Exec(ctx, updateAutoTopupAmount, arg.Amount, arg.TopupRuleID, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE pockets.transactions
SET amount = $1, is_inflow = $2, tx_date = $3, note = $4, user_edited = $5
WHERE id = $6
`

type UpdateTransactionParams struct {
	Amount     pgtype.Numeric `json:"amount"`
	IsInflow   bool           `json:"is_inflow"`
	TxDate     pgtype.Date    `json:"tx_date"`
	Note       pgtype.Text    `json:"note"`
	UserEdited bool           `json:"user_edited"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.Amount,
		arg.IsInflow,
		arg.TxDate,
		arg.Note,
		arg.UserEdited,
		arg.ID,
	)
	return err
}
