// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type QuestsPushSubscription struct {
	ID        int64              `json:"id"`
	Endpoint  string             `json:"endpoint"`
	P256dh    string             `json:"p256dh"`
	Auth      string             `json:"auth"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QuestsQuest struct {
	ID                     int64              `json:"id"`
	Title                  string             `json:"title"`
	Description            pgtype.Text        `json:"description"`
	QuestType              string             `json:"quest_type"`
	QuestDate              pgtype.Date        `json:"quest_date"`
	QuestLineID            pgtype.Int8        `json:"quest_line_id"`
	QuestGiver             pgtype.Text        `json:"quest_giver"`
	ReminderTime           pgtype.Time        `json:"reminder_time"`
	ReminderSentAt         pgtype.Date        `json:"reminder_sent_at"`
	SortOrder              int32              `json:"sort_order"`
	Status                 string             `json:"status"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	FailedAt               pgtype.Timestamptz `json:"failed_at"`
	RecurrenceType         pgtype.Text        `json:"recurrence_type"`
	RecurrenceN            pgtype.Int4        `json:"recurrence_n"`
	RecurrenceUnit         pgtype.Text        `json:"recurrence_unit"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	RecurrenceEndDate      pgtype.Date        `json:"recurrence_end_date"`
	RecurrenceInstance     pgtype.Int4        `json:"recurrence_instance"`
	RecurrenceMaxInstances pgtype.Int4        `json:"recurrence_max_instances"`
}

type QuestsQuestLine struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	QuestType   pgtype.Text        `json:"quest_type"`
}
