// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package sqlc

import (
	"context"
)

const createPushSubscription = `-- name: CreatePushSubscription :one

INSERT INTO quests.push_subscriptions (endpoint, p256dh, auth)
VALUES ($1, $2, $3)
ON CONFLICT (endpoint) DO UPDATE SET p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
RETURNING id
`

type CreatePushSubscriptionParams struct {
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

// Cellarium Quests — push subscription queries
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPushSubscription, arg.Endpoint, arg.P256dh, arg.Auth)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM quests.push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, endpoint)
	return err
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, endpoint, p256dh, auth, created_at FROM quests.push_subscriptions
`

func (q *Queries) ListPushSubscriptions(ctx context.Context) ([]QuestsPushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsPushSubscription
	for rows.Next() {
		var i QuestsPushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
