// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteQuest(ctx context.Context, id int64) error
	// Cellarium Quests — push subscription queries
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (int64, error)
	// Cellarium Quests — quest queries
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateQuest(ctx context.Context, arg CreateQuestParams) (int64, error)
	// Cellarium Quests — quest line queries
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateQuestLine(ctx context.Context, arg CreateQuestLineParams) (int64, error)
	DeletePushSubscription(ctx context.Context, endpoint string) error
	DeleteQuest(ctx context.Context, id int64) error
	DeleteQuestLine(ctx context.Context, id int64) error
	FailOverdueQuests(ctx context.Context, today pgtype.Date) ([]QuestsQuest, error)
	FailQuest(ctx context.Context, id int64) error
	GetQuest(ctx context.Context, id int64) (QuestsQuest, error)
	GetQuestLine(ctx context.Context, id int64) (GetQuestLineRow, error)
	ListActiveAndCompletedQuests(ctx context.Context) ([]QuestsQuest, error)
	ListActiveQuests(ctx context.Context) ([]QuestsQuest, error)
	ListDueReminders(ctx context.Context, arg ListDueRemindersParams) ([]QuestsQuest, error)
	ListPushSubscriptions(ctx context.Context) ([]QuestsPushSubscription, error)
	ListQuestGivers(ctx context.Context) ([]pgtype.Text, error)
	ListQuestLines(ctx context.Context) ([]ListQuestLinesRow, error)
	ListQuestLog(ctx context.Context) ([]QuestsQuest, error)
	ListTodayQuests(ctx context.Context, questDate pgtype.Date) ([]QuestsQuest, error)
	MarkReminderSent(ctx context.Context, arg MarkReminderSentParams) error
	UncompleteQuest(ctx context.Context, id int64) error
	UncompleteQuestAndResetDate(ctx context.Context, arg UncompleteQuestAndResetDateParams) error
	UpdateQuest(ctx context.Context, arg UpdateQuestParams) error
	UpdateQuestLine(ctx context.Context, arg UpdateQuestLineParams) error
	UpdateQuestLineSortOrder(ctx context.Context, arg UpdateQuestLineSortOrderParams) error
	UpdateQuestSortOrder(ctx context.Context, arg UpdateQuestSortOrderParams) error
	UpdateQuestTypeByLine(ctx context.Context, arg UpdateQuestTypeByLineParams) error
}

var _ Querier = (*Queries)(nil)
