// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quest_lines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestLine = `-- name: CreateQuestLine :one

INSERT INTO quests.quest_lines (name, description, sort_order, quest_type)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateQuestLineParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	QuestType   pgtype.Text `json:"quest_type"`
}

// Cellarium Quests — quest line queries
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateQuestLine(ctx context.Context, arg CreateQuestLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuestLine,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.QuestType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteQuestLine = `-- name: DeleteQuestLine :exec
DELETE FROM quests.quest_lines WHERE id = $1
`

func (q *Queries) DeleteQuestLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuestLine, id)
	return err
}

const getQuestLine = `-- name: GetQuestLine :one
SELECT id, name, description, sort_order, quest_type, created_at FROM quests.quest_lines WHERE id = $1
`

type GetQuestLineRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	QuestType   pgtype.Text        `json:"quest_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetQuestLine(ctx context.Context, id int64) (GetQuestLineRow, error) {
	row := q.db.QueryRow(ctx, getQuestLine, id)
	var i GetQuestLineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.QuestType,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestLines = `-- name: ListQuestLines :many
SELECT id, name, description, sort_order, quest_type, created_at FROM quests.quest_lines ORDER BY sort_order ASC, id ASC
`

type ListQuestLinesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	QuestType   pgtype.Text        `json:"quest_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListQuestLines(ctx context.Context) ([]ListQuestLinesRow, error) {
	rows, err := q.db.Query(ctx, listQuestLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestLinesRow
	for rows.Next() {
		var i ListQuestLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.QuestType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestLinesWithCount = `-- name: ListQuestLinesWithCount :many
SELECT ql.id, ql.name, ql.description, ql.sort_order, ql.quest_type, ql.created_at,
       (SELECT count(*) FROM quests.quests q WHERE q.quest_line_id = ql.id AND q.status = 'active') AS active_quest_count
FROM quests.quest_lines ql
ORDER BY ql.sort_order ASC, ql.id ASC
`

type ListQuestLinesWithCountRow struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	SortOrder        int32              `json:"sort_order"`
	QuestType        pgtype.Text        `json:"quest_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActiveQuestCount int64              `json:"active_quest_count"`
}

func (q *Queries) ListQuestLinesWithCount(ctx context.Context) ([]ListQuestLinesWithCountRow, error) {
	rows, err := q.db.Query(ctx, listQuestLinesWithCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestLinesWithCountRow
	for rows.Next() {
		var i ListQuestLinesWithCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.QuestType,
			&i.CreatedAt,
			&i.ActiveQuestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestLine = `-- name: UpdateQuestLine :exec
UPDATE quests.quest_lines SET name = $1, description = $2, sort_order = $3, quest_type = $4 WHERE id = $5
`

type UpdateQuestLineParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	QuestType   pgtype.Text `json:"quest_type"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateQuestLine(ctx context.Context, arg UpdateQuestLineParams) error {
	_, err := q.db.Exec(ctx, updateQuestLine,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.QuestType,
		arg.ID,
	)
	return err
}

const updateQuestLineSortOrder = `-- name: UpdateQuestLineSortOrder :exec
UPDATE quests.quest_lines SET sort_order = $1 WHERE id = $2
`

type UpdateQuestLineSortOrderParams struct {
	SortOrder int32 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateQuestLineSortOrder(ctx context.Context, arg UpdateQuestLineSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateQuestLineSortOrder, arg.SortOrder, arg.ID)
	return err
}
