// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quest_lines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestLine = `-- name: CreateQuestLine :one

INSERT INTO quests.quest_lines (name, description, sort_order)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateQuestLineParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
}

// Cellarium Quests — quest line queries
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateQuestLine(ctx context.Context, arg CreateQuestLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuestLine, arg.Name, arg.Description, arg.SortOrder)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteQuestLine = `-- name: DeleteQuestLine :exec
DELETE FROM quests.quest_lines WHERE id = $1
`

func (q *Queries) DeleteQuestLine(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuestLine, id)
	return err
}

const getQuestLine = `-- name: GetQuestLine :one
SELECT id, name, description, sort_order, created_at FROM quests.quest_lines WHERE id = $1
`

func (q *Queries) GetQuestLine(ctx context.Context, id int64) (QuestsQuestLine, error) {
	row := q.db.QueryRow(ctx, getQuestLine, id)
	var i QuestsQuestLine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestLines = `-- name: ListQuestLines :many
SELECT id, name, description, sort_order, created_at FROM quests.quest_lines ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListQuestLines(ctx context.Context) ([]QuestsQuestLine, error) {
	rows, err := q.db.Query(ctx, listQuestLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuestLine
	for rows.Next() {
		var i QuestsQuestLine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestLine = `-- name: UpdateQuestLine :exec
UPDATE quests.quest_lines SET name = $1, description = $2, sort_order = $3 WHERE id = $4
`

type UpdateQuestLineParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateQuestLine(ctx context.Context, arg UpdateQuestLineParams) error {
	_, err := q.db.Exec(ctx, updateQuestLine,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
