// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeQuest = `-- name: CompleteQuest :exec
UPDATE quests.quests SET status = 'completed', completed_at = now() WHERE id = $1
`

func (q *Queries) CompleteQuest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeQuest, id)
	return err
}

const createQuest = `-- name: CreateQuest :one

INSERT INTO quests.quests (title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, sort_order, recurrence_type, recurrence_n, recurrence_unit, recurrence_end_date, recurrence_instance, recurrence_max_instances)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id
`

type CreateQuestParams struct {
	Title                  string      `json:"title"`
	Description            pgtype.Text `json:"description"`
	QuestType              string      `json:"quest_type"`
	QuestDate              pgtype.Date `json:"quest_date"`
	QuestLineID            pgtype.Int8 `json:"quest_line_id"`
	QuestGiver             pgtype.Text `json:"quest_giver"`
	ReminderTime           pgtype.Time `json:"reminder_time"`
	SortOrder              int32       `json:"sort_order"`
	RecurrenceType         pgtype.Text `json:"recurrence_type"`
	RecurrenceN            pgtype.Int4 `json:"recurrence_n"`
	RecurrenceUnit         pgtype.Text `json:"recurrence_unit"`
	RecurrenceEndDate      pgtype.Date `json:"recurrence_end_date"`
	RecurrenceInstance     pgtype.Int4 `json:"recurrence_instance"`
	RecurrenceMaxInstances pgtype.Int4 `json:"recurrence_max_instances"`
}

// Cellarium Quests — quest queries
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.Title,
		arg.Description,
		arg.QuestType,
		arg.QuestDate,
		arg.QuestLineID,
		arg.QuestGiver,
		arg.ReminderTime,
		arg.SortOrder,
		arg.RecurrenceType,
		arg.RecurrenceN,
		arg.RecurrenceUnit,
		arg.RecurrenceEndDate,
		arg.RecurrenceInstance,
		arg.RecurrenceMaxInstances,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteQuest = `-- name: DeleteQuest :exec
DELETE FROM quests.quests WHERE id = $1
`

func (q *Queries) DeleteQuest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuest, id)
	return err
}

const failOverdueQuests = `-- name: FailOverdueQuests :many
UPDATE quests.quests SET status = 'failed', failed_at = now() WHERE status = 'active' AND quest_date IS NOT NULL AND quest_date < $1 RETURNING id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
`

func (q *Queries) FailOverdueQuests(ctx context.Context, today pgtype.Date) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, failOverdueQuests, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failQuest = `-- name: FailQuest :exec
UPDATE quests.quests SET status = 'failed', failed_at = now() WHERE id = $1
`

func (q *Queries) FailQuest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, failQuest, id)
	return err
}

const getQuest = `-- name: GetQuest :one
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE id = $1
`

func (q *Queries) GetQuest(ctx context.Context, id int64) (QuestsQuest, error) {
	row := q.db.QueryRow(ctx, getQuest, id)
	var i QuestsQuest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.QuestType,
		&i.QuestDate,
		&i.QuestLineID,
		&i.QuestGiver,
		&i.ReminderTime,
		&i.ReminderSentAt,
		&i.SortOrder,
		&i.Status,
		&i.CompletedAt,
		&i.FailedAt,
		&i.RecurrenceType,
		&i.RecurrenceN,
		&i.RecurrenceUnit,
		&i.CreatedAt,
		&i.RecurrenceEndDate,
		&i.RecurrenceInstance,
		&i.RecurrenceMaxInstances,
	)
	return i, err
}

const listActiveAndCompletedQuests = `-- name: ListActiveAndCompletedQuests :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE status IN ('active', 'completed') ORDER BY quest_type ASC, sort_order ASC, id ASC
`

func (q *Queries) ListActiveAndCompletedQuests(ctx context.Context) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listActiveAndCompletedQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveQuests = `-- name: ListActiveQuests :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE status = 'active' ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListActiveQuests(ctx context.Context) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listActiveQuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE status = 'active' AND reminder_time IS NOT NULL AND reminder_time <= $1 AND (quest_date IS NULL OR quest_date = $2) AND (reminder_sent_at IS NULL OR reminder_sent_at < $2)
`

type ListDueRemindersParams struct {
	NowTime pgtype.Time `json:"now_time"`
	Today   pgtype.Date `json:"today"`
}

func (q *Queries) ListDueReminders(ctx context.Context, arg ListDueRemindersParams) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listDueReminders, arg.NowTime, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestGivers = `-- name: ListQuestGivers :many
SELECT DISTINCT quest_giver FROM quests.quests WHERE quest_giver IS NOT NULL AND quest_giver <> '' ORDER BY quest_giver ASC
`

func (q *Queries) ListQuestGivers(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listQuestGivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var quest_giver pgtype.Text
		if err := rows.Scan(&quest_giver); err != nil {
			return nil, err
		}
		items = append(items, quest_giver)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestLog = `-- name: ListQuestLog :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE status IN ('completed','failed') ORDER BY COALESCE(completed_at, failed_at) DESC NULLS LAST, id DESC
`

func (q *Queries) ListQuestLog(ctx context.Context) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listQuestLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsByLine = `-- name: ListQuestsByLine :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver,
       reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at,
       recurrence_type, recurrence_n, recurrence_unit, created_at,
       recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE quest_line_id = $1
ORDER BY
  CASE status WHEN 'completed' THEN 0 WHEN 'failed' THEN 1 WHEN 'active' THEN 2 END ASC,
  CASE status WHEN 'completed' THEN completed_at WHEN 'failed' THEN failed_at ELSE NULL END ASC NULLS LAST,
  quest_date ASC NULLS LAST,
  id ASC
`

func (q *Queries) ListQuestsByLine(ctx context.Context, questLineID pgtype.Int8) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listQuestsByLine, questLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayQuests = `-- name: ListTodayQuests :many
SELECT id, title, description, quest_type, quest_date, quest_line_id, quest_giver, reminder_time, reminder_sent_at, sort_order, status, completed_at, failed_at, recurrence_type, recurrence_n, recurrence_unit, created_at, recurrence_end_date, recurrence_instance, recurrence_max_instances
FROM quests.quests WHERE status = 'active' AND quest_date = $1 ORDER BY quest_type ASC, sort_order ASC, id ASC
`

func (q *Queries) ListTodayQuests(ctx context.Context, questDate pgtype.Date) ([]QuestsQuest, error) {
	rows, err := q.db.Query(ctx, listTodayQuests, questDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestsQuest
	for rows.Next() {
		var i QuestsQuest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.QuestType,
			&i.QuestDate,
			&i.QuestLineID,
			&i.QuestGiver,
			&i.ReminderTime,
			&i.ReminderSentAt,
			&i.SortOrder,
			&i.Status,
			&i.CompletedAt,
			&i.FailedAt,
			&i.RecurrenceType,
			&i.RecurrenceN,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.RecurrenceEndDate,
			&i.RecurrenceInstance,
			&i.RecurrenceMaxInstances,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE quests.quests SET reminder_sent_at = $1 WHERE id = $2
`

type MarkReminderSentParams struct {
	Today pgtype.Date `json:"today"`
	ID    int64       `json:"id"`
}

func (q *Queries) MarkReminderSent(ctx context.Context, arg MarkReminderSentParams) error {
	_, err := q.db.Exec(ctx, markReminderSent, arg.Today, arg.ID)
	return err
}

const uncompleteQuest = `-- name: UncompleteQuest :exec
UPDATE quests.quests SET status = 'active', completed_at = NULL WHERE id = $1
`

func (q *Queries) UncompleteQuest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, uncompleteQuest, id)
	return err
}

const uncompleteQuestAndResetDate = `-- name: UncompleteQuestAndResetDate :exec
UPDATE quests.quests SET status = 'active', completed_at = NULL, quest_date = $1 WHERE id = $2
`

type UncompleteQuestAndResetDateParams struct {
	QuestDate pgtype.Date `json:"quest_date"`
	ID        int64       `json:"id"`
}

func (q *Queries) UncompleteQuestAndResetDate(ctx context.Context, arg UncompleteQuestAndResetDateParams) error {
	_, err := q.db.Exec(ctx, uncompleteQuestAndResetDate, arg.QuestDate, arg.ID)
	return err
}

const updateQuest = `-- name: UpdateQuest :exec
UPDATE quests.quests SET title = $1, description = $2, quest_type = $3, quest_date = $4, quest_line_id = $5, quest_giver = $6, reminder_time = $7, sort_order = $8, recurrence_type = $9, recurrence_n = $10, recurrence_unit = $11, recurrence_end_date = $12, recurrence_instance = $13, recurrence_max_instances = $14 WHERE id = $15
`

type UpdateQuestParams struct {
	Title                  string      `json:"title"`
	Description            pgtype.Text `json:"description"`
	QuestType              string      `json:"quest_type"`
	QuestDate              pgtype.Date `json:"quest_date"`
	QuestLineID            pgtype.Int8 `json:"quest_line_id"`
	QuestGiver             pgtype.Text `json:"quest_giver"`
	ReminderTime           pgtype.Time `json:"reminder_time"`
	SortOrder              int32       `json:"sort_order"`
	RecurrenceType         pgtype.Text `json:"recurrence_type"`
	RecurrenceN            pgtype.Int4 `json:"recurrence_n"`
	RecurrenceUnit         pgtype.Text `json:"recurrence_unit"`
	RecurrenceEndDate      pgtype.Date `json:"recurrence_end_date"`
	RecurrenceInstance     pgtype.Int4 `json:"recurrence_instance"`
	RecurrenceMaxInstances pgtype.Int4 `json:"recurrence_max_instances"`
	ID                     int64       `json:"id"`
}

func (q *Queries) UpdateQuest(ctx context.Context, arg UpdateQuestParams) error {
	_, err := q.db.Exec(ctx, updateQuest,
		arg.Title,
		arg.Description,
		arg.QuestType,
		arg.QuestDate,
		arg.QuestLineID,
		arg.QuestGiver,
		arg.ReminderTime,
		arg.SortOrder,
		arg.RecurrenceType,
		arg.RecurrenceN,
		arg.RecurrenceUnit,
		arg.RecurrenceEndDate,
		arg.RecurrenceInstance,
		arg.RecurrenceMaxInstances,
		arg.ID,
	)
	return err
}

const updateQuestSortOrder = `-- name: UpdateQuestSortOrder :exec
UPDATE quests.quests SET sort_order = $1 WHERE id = $2
`

type UpdateQuestSortOrderParams struct {
	SortOrder int32 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateQuestSortOrder(ctx context.Context, arg UpdateQuestSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateQuestSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateQuestTypeByLine = `-- name: UpdateQuestTypeByLine :exec
UPDATE quests.quests SET quest_type = $1 WHERE quest_line_id = $2
`

type UpdateQuestTypeByLineParams struct {
	QuestType   string      `json:"quest_type"`
	QuestLineID pgtype.Int8 `json:"quest_line_id"`
}

func (q *Queries) UpdateQuestTypeByLine(ctx context.Context, arg UpdateQuestTypeByLineParams) error {
	_, err := q.db.Exec(ctx, updateQuestTypeByLine, arg.QuestType, arg.QuestLineID)
	return err
}
