// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one

INSERT INTO receipts.entries (value, entry_date, note)
VALUES ($1, $2, $3)
RETURNING id, value, entry_date, note, created_at
`

type CreateEntryParams struct {
	Value     pgtype.Numeric `json:"value"`
	EntryDate pgtype.Date    `json:"entry_date"`
	Note      string         `json:"note"`
}

// Cellarium Receipt Tracker — receipt entry queries
// Copyright (C) 2026 Maroš Kučera
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (ReceiptsEntry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.Value, arg.EntryDate, arg.Note)
	var i ReceiptsEntry
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.EntryDate,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
