// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReceiptsEntry struct {
	ID        int64              `json:"id"`
	Value     pgtype.Numeric     `json:"value"`
	EntryDate pgtype.Date        `json:"entry_date"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Batch     int32              `json:"batch"`
	Paid      bool               `json:"paid"`
}
