// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	// Cellarium Receipt Tracker — receipt entry queries
	// Copyright (C) 2026 Maroš Kučera
	//
	// This program is free software: you can redistribute it and/or modify
	// it under the terms of the GNU General Public License as published by
	// the Free Software Foundation, either version 3 of the License, or
	// (at your option) any later version.
	//
	// This program is distributed in the hope that it will be useful,
	// but WITHOUT ANY WARRANTY; without even the implied warranty of
	// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	// GNU General Public License for more details.
	//
	// You should have received a copy of the GNU General Public License
	// along with this program.  If not, see <https://www.gnu.org/licenses/>.
	CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error)
	ListUnpaidEntries(ctx context.Context) ([]ListUnpaidEntriesRow, error)
	MarkEntriesPaid(ctx context.Context, ids []int64) error
}

var _ Querier = (*Queries)(nil)
