// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasEntries = `-- name: HasEntries :one
SELECT EXISTS(SELECT 1 FROM loans.entries) AS has_entries
`

func (q *Queries) HasEntries(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasEntries)
	var has_entries bool
	err := row.Scan(&has_entries)
	return has_entries, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO loans.entries (amount, entry_date) VALUES ($1, $2) RETURNING id
`

type CreateEntryParams struct {
	Amount    pgtype.Numeric `json:"amount"`
	EntryDate pgtype.Date    `json:"entry_date"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.Amount, arg.EntryDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLoanEntry = `-- name: GetLoanEntry :one
SELECT id, amount, entry_date FROM loans.entries ORDER BY id ASC LIMIT 1
`

type GetLoanEntryRow struct {
	ID        int64          `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	EntryDate pgtype.Date    `json:"entry_date"`
}

func (q *Queries) GetLoanEntry(ctx context.Context) (GetLoanEntryRow, error) {
	row := q.db.QueryRow(ctx, getLoanEntry)
	var i GetLoanEntryRow
	err := row.Scan(&i.ID, &i.Amount, &i.EntryDate)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS balance FROM loans.entries
`

func (q *Queries) GetBalance(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBalance)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const getTotalRepaid = `-- name: GetTotalRepaid :one
SELECT COALESCE(-SUM(amount), 0)::NUMERIC(12,2) AS total FROM loans.entries WHERE amount < 0
`

func (q *Queries) GetTotalRepaid(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalRepaid)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getLastPayment = `-- name: GetLastPayment :one
SELECT id, amount, entry_date FROM loans.entries WHERE amount < 0 ORDER BY id DESC LIMIT 1
`

type GetLastPaymentRow struct {
	ID        int64          `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	EntryDate pgtype.Date    `json:"entry_date"`
}

func (q *Queries) GetLastPayment(ctx context.Context) (GetLastPaymentRow, error) {
	row := q.db.QueryRow(ctx, getLastPayment)
	var i GetLastPaymentRow
	err := row.Scan(&i.ID, &i.Amount, &i.EntryDate)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, amount, entry_date FROM loans.entries WHERE amount < 0 ORDER BY entry_date ASC, id ASC
`

type ListPaymentsRow struct {
	ID        int64          `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	EntryDate pgtype.Date    `json:"entry_date"`
}

func (q *Queries) ListPayments(ctx context.Context) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsRow
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(&i.ID, &i.Amount, &i.EntryDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
