// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LoansEntry struct {
	ID        int64              `json:"id"`
	Amount    pgtype.Numeric     `json:"amount"`
	EntryDate pgtype.Date        `json:"entry_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
