// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error)
	GetBalance(ctx context.Context) (pgtype.Numeric, error)
	GetLastPayment(ctx context.Context) (GetLastPaymentRow, error)
	GetLoanEntry(ctx context.Context) (GetLoanEntryRow, error)
	GetTotalRepaid(ctx context.Context) (pgtype.Numeric, error)
	HasEntries(ctx context.Context) (bool, error)
	ListPayments(ctx context.Context) ([]ListPaymentsRow, error)
}

var _ Querier = (*Queries)(nil)
